Riak 2.9.6
rbkmoney/image-riak-base pull request #14
Opened 2020-08-14 10:11 UTC by kpy3

2020-08-17 14:28 UTC, niku64 requested changes

2020-08-17 14:28 UTC, niku64 commented on files/install-riak.sh
> +export GIT_BRANCH_RIAK=riak-2.9.7
2.9.7?

2020-08-17 14:29 UTC, kpy3 commented on files/install-riak.sh
> +export GIT_BRANCH_RIAK=riak-2.9.7
Они там накосячили с тегом 2.9.6 и просто сделали новый

2020-08-18 09:44 UTC, niku64 approved these changes

2020-08-18 09:44 UTC, niku64 commented on files/riak.patch
> +        {rel, "riak", "2.9.6",
А здесь должно быть 2.9.6?

2020-08-18 09:58 UTC, kpy3 commented on files/riak.patch
> +        {rel, "riak", "2.9.6",
https://github.com/basho/riak/blob/riak-2.9.7/rel/reltool.config

2020-08-25 14:34 UTC, merged